# path relative to where you run snakemake

# gene annotation file, can be gtf or gff
genomeAnno: "testdata/GRCm38.83.chr19.gtf"
# genome sequence
genomeFasta: "testdata/chr19.fa"
# result directory of NGSPipe
resultsDir: "results/result"
reportsDir: "results/report"

# sample list file
samplesList: "testdata/samples_chipseq.xls"
# sample file directory
samplesDir: "testdata"
# fastq suffix, read1
read1Suffix: "_R1.fq.gz"
read2Suffix: "_R2.fq.gz"
