# Project information
site_name: NGSPipeDb Document
site_url: https://xuanblo.github.io/NGSPipeDb/
site_author: Xuan Zhang
site_description: NGSPipeDb is a pipeline

# Repository
repo_url: https://github.com/xuanblo/NGSPipeDb/
edit_uri: 'edit/master/mkdocs/markdowns/'
docs_dir: markdowns
site_dir: docs

# Copyright
copyright: Bioinformatics Group, XTBG, 2021

plugins:
    - search:
#    - mkdocs-versioning:
#        version: 0.3.0
    - mkdocs_pymdownx_material_extras:

# Navigation
nav:
- Home:
    - Getting start: index.md
    - NGSPipeDb Tutorial: NGSPipeDb.md
- Pipelines:
    - NGSPipe RNA-seq: NGSPipe-RNA-seq.md
    - NGSPipe ChIP-seq: NGSPipe-ChIP-seq.md
    - NGSPipe resequecing: NGSPipe-resequecing.md
    - NGSDb: NGSDb.md
- Learning materials:
    - Linux & shell basic: linux.md
    - NGS analysis: ngs.md
    - Conda: conda.md
- Change logs: changelog.md

# Theme
theme:
    name: material
    palette:
        scheme: dracula
        primary: deep purple
        accent: deep purple
    font:
        text: Roboto
        code: Roboto Mono
    features:
        - navigation.tabs

markdown_extensions:
    - pymdownx.tabbed:
    - pymdownx.highlight:
    - pymdownx.inlinehilite:
    - pymdownx.superfences:
    - admonition: # note info
    - pymdownx.details:
    - pymdownx.saneheaders:
    - markdown.extensions.smarty:
        smart_quotes: false

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk