site_name: NGSPipeDb Document
repo_url: https://github.com/xuanblo/NGSPipeDb/mkdocs
site_url: https://xuanblo.github.io/NGSPipeDb/
site_description: NGSPipeDb is a pipeline
copyright: Bioinformatics Group, XTBG, 2021
docs_dir: markdowns
site_dir: docs
lang: en
plugins:
    - search:

nav:
    - Getting start: index.md
    - NGSPipeDb Tutorial: NGSPipeDb.md
    - NGSPipe RNA-seq: NGSPipe-RNA-seq.md
    - NGSPipe ChIP-seq: NGSPipe-ChIP-seq.md
    - NGSPipe resequecing: NGSPipe-resequecing.md
    - NGSDb: NGSDb.md
    - Linux basic: linux.md

theme: readthedocs