site_name: My Docs
site_name: NGSPipeDb Document
repo_url: https://github.com/xuanblo/NGSPipeDb/mkdocs
site_url: https://xuanblo.github.io/NGSPipeDb/
site_description: NGSPipeDb is a pipeline
copyright: Bioinformatics Group, XTBG, 2021
docs_dir: markdowns
site_dir: docs
lang: en
plugins:
    - search:

nav:
    - NGSPipeDb usage: index.md
    - Linux basic: linux.md
    - RNA-seq best practice: rnaseq.md

theme: readthedocs